version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: uvicorn src:app --workers 1 --host ${APP_HOST} --port ${APP_PORT} --reload --reload-dir . --log-config=log_config.ini
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
