[build]
builder = "NIXPACKS"
buildCommand = "pip install poetry && poetry install --no-dev"

[deploy]
startCommand = "uvicorn backend:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"