name: linter-check

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install uv
      - run: uv sync
      - run: uv run flake8 src
